using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace XmlSerDe.Tests
{
    /// <summary>
    /// Шапка сгенерированных файлов - и то, ради чего она глушит предупреждения
    /// целиком.
    ///
    /// Сгенерированный код компилируется в сборке потребителя, с его настройками
    /// предупреждений. Потребитель этот файл не писал и починить в нём ничего не
    /// может, поэтому генератор глушит в нём всё подряд: перечислить поимённо
    /// можно только то, про что мы догадались, а включает предупреждения не тот,
    /// кто догадался. С <c>TreatWarningsAsErrors</c> любое незаглушенное
    /// предупреждение означает, что проект потребителя не собирается вовсе.
    ///
    /// Цена такой шапки - потерянный сигнал у нас самих, и платить её незачем:
    /// <see cref="GeneratedCode_WithoutPrelude_RaisesNoWarningsBeyondTheKnownOnes"/>
    /// компилирует тот же код со снятой шапкой и требует, чтобы предупреждений не
    /// было ни одного, кроме названных здесь поимённо. То есть глушение работает
    /// наружу, а внутрь - нет.
    /// </summary>
    public class GeneratedPreludeFixture
    {
        /// <summary>
        /// Пишется здесь второй раз намеренно: это не переиспользование константы
        /// генератора, а проверка договорённости. Изменится шапка - тест должен
        /// упасть и потребовать осознанного решения, а не молча подстроиться.
        /// </summary>
        private const string AutoGeneratedLine = "// <auto-generated/>";

        private const string PragmaLine = "#pragma warning disable";

        /// <summary>
        /// Предупреждения, которые сгенерированный код даёт по существу, а не по
        /// недосмотру, - каждое снято прогоном:
        ///
        /// <list type="bullet">
        /// <item><c>CS8981</c> - алиас <c>roschar</c> целиком в нижнем регистре.
        /// Имя выбрано осознанно, оно читается как примитив; 20 штук на проект.</item>
        /// </list>
        ///
        /// Отдельно стоит <c>CS1591</c> (нет xml-комментария у публичного члена):
        /// в этой компиляции его не видно, потому что документация не собирается, а
        /// у потребителя с <c>GenerateDocumentationFile</c> это 654 предупреждения.
        /// Дописывать <c>///</c> к сгенерированному коду смысла нет - его читают
        /// отладчиком, а не IntelliSense, - поэтому он остаётся на шапке.
        /// </summary>
        private static readonly HashSet<string> KnownWarnings = new HashSet<string>
        {
            "CS8981",
        };

        private const string Source = @"
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Xml.Serialization;
using XmlSerDe;

namespace Sample
{
    public enum Kind { One = 1, Two = 2 }

    [XmlInclude(typeof(Derived))]
    public class Base
    {
        [XmlAttribute(""id"")]
        public int Id { get; set; }

        public string Name { get; set; }
    }

    public class Derived : Base
    {
        public Kind Kind { get; set; }

        [DefaultValue(0)]
        public int Weight { get; set; }
    }

    public class Holder
    {
        public Base Item { get; set; }
        public List<Derived> Items { get; set; }
        public int[] Numbers { get; set; }
        public byte[] Blob { get; set; }
        public DateTime? When { get; set; }
        public Note Note { get; set; }
    }

    //текст без соседей-элементов: смешанное содержимое не поддерживается вовсе
    public class Note
    {
        [XmlAttribute(""id"")]
        public int Id { get; set; }

        [XmlText]
        public string Body { get; set; }
    }

    [XmlSubject(typeof(Base), false)]
    [XmlSubject(typeof(Derived), false)]
    [XmlSubject(typeof(Note), false)]
    [XmlSubject(typeof(Holder), true)]
    public partial class Host { }
}
";

        [Fact]
        public void EveryGeneratedFile_StartsWithThePrelude()
        {
            var sources = Generate();

            Assert.NotEmpty(sources);

            foreach (var pair in sources)
            {
                var lines = pair.Value.Replace("\r\n", "\n").Split('\n');

                Assert.True(
                    lines.Length > 1,
                    pair.Key + ": сгенерированный файл короче собственной шапки"
                    );
                Assert.True(
                    lines[0] == AutoGeneratedLine,
                    pair.Key + ": первая строка - '" + lines[0] + "', а должна быть '" + AutoGeneratedLine + "'"
                    );
                Assert.True(
                    lines[1] == PragmaLine,
                    pair.Key + ": вторая строка - '" + lines[1] + "', а должна быть '" + PragmaLine + "'"
                    );
            }
        }

        /// <summary>
        /// Шапка снимается, и код компилируется голым. Всё, что здесь всплывёт сверх
        /// <see cref="KnownWarnings"/>, у потребителя молча глушится шапкой - то есть
        /// увидеть это можно только здесь.
        /// </summary>
        [Fact]
        public void GeneratedCode_WithoutPrelude_RaisesNoWarningsBeyondTheKnownOnes()
        {
            var sources = Generate();

            var trees = new List<SyntaxTree>
            {
                CSharpSyntaxTree.ParseText(Source, path: "source.cs"),
            };

            foreach (var pair in sources)
            {
                trees.Add(
                    CSharpSyntaxTree.ParseText(StripPrelude(pair.Value), path: pair.Key)
                    );
            }

            var compilation = CSharpCompilation.Create(
                "GeneratedPreludeFixtureAssembly",
                trees,
                GeneratorHarness.References(),
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
                );

            var unexpected = compilation.GetDiagnostics()
                .Where(d => d.Severity == DiagnosticSeverity.Warning)
                .Where(d => !KnownWarnings.Contains(d.Id))
                .Select(d => d.ToString())
                .Distinct()
                .ToList();

            Assert.True(
                unexpected.Count == 0,
                "сгенерированный код предупреждает о том, чего нет в списке известных:"
                    + Environment.NewLine
                    + string.Join(Environment.NewLine, unexpected)
                );
        }

        private static string StripPrelude(string source)
        {
            var index = source.IndexOf(PragmaLine, StringComparison.Ordinal);

            Assert.True(index >= 0, "шапки нет вовсе, снимать нечего");

            //строки шапки заменяются на пустые, а не выбрасываются: номера строк в
            //диагностике должны остаться теми же, что у потребителя
            return new string('\n', CountNewLines(source.Substring(0, index + PragmaLine.Length)))
                + source.Substring(index + PragmaLine.Length);
        }

        private static int CountNewLines(string text)
        {
            var count = 0;
            foreach (var c in text)
            {
                if (c == '\n')
                {
                    count++;
                }
            }

            return count;
        }

        private static Dictionary<string, string> Generate()
        {
            var compilation = CSharpCompilation.Create(
                "GeneratedPreludeFixtureAssembly",
                new[] { CSharpSyntaxTree.ParseText(Source, path: "source.cs"), },
                GeneratorHarness.References(),
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
                );

            var driver = CSharpGeneratorDriver.Create(
                new[] { new global::XmlSerDe.Generator.XmlDeserializeGenerator().AsSourceGenerator(), }
                );

            driver
                .RunGeneratorsAndUpdateCompilation(compilation, out var output, out var generatorDiagnostics)
                .GetRunResult();

            Assert.True(
                generatorDiagnostics.All(d => d.Severity != DiagnosticSeverity.Error),
                "generator errors:" + Environment.NewLine
                    + string.Join(Environment.NewLine, generatorDiagnostics.Select(d => d.ToString()))
                );

            var result = new Dictionary<string, string>();
            foreach (var tree in output.SyntaxTrees)
            {
                if (tree.FilePath.EndsWith(".g.cs", StringComparison.Ordinal))
                {
                    result[tree.FilePath] = tree.ToString();
                }
            }

            return result;
        }
    }
}
