<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net10.0</TargetFrameworks>
    <LangVersion>Latest</LangVersion>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>nullable;CS8766;CS8767</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XmlSerDe.Common\XmlSerDe.Common.csproj" />
  </ItemGroup>

</Project>
